version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - graphviz
    - texlive-publishers
  jobs:
    post_build:
      - python -c 'import ccd_snr; ccd_snr.pdf()'
      - mv ccd_snr/ccd-euv-snr.pdf $READTHEDOCS_OUTPUT/pdf/

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
